# √Ä modifier avec le nom et la description du site
site_name: "Journal de bord de math√©matiques au CSJA"
site_description: Les progressions communes, les cahiers de texte, les supports de cours, les exercices et les √©valuations.</br>   
    Choisissez l'onglet de votre classe ou consultez la page des liens pour tous les niveaux

site_url: !ENV [CI_PAGES_URL, "http://127.0.0.1:8000/"] 
site_author: !ENV [CI_COMMIT_AUTHOR, "Nizar MOUSSATAT"]
repo_url: !ENV [CI_PROJECT_URL, "https://github.com/moussatat/journal"]  # la sauvegarde github du code source du site
edit_uri: "./edit/main/docs/" 

use_directory_urls: true # REQUIS pour pyodide-mkdocs-theme
 
# √Ä modifier, avec votre nom et la licence choisie
# Ou activer dans my_hooks pour configuration automatique
copyright: |  
    <a href="https://moussatat.github.io/about">Nizar MOUSSATAT, 2024</a>
    <a style="vertical-align:middle" rel="Sous licence CC BY-NC-SA 4.0" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Sous licence CC BY-NC-SA 4.0" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png"/></a>  

# √Ä modifier, avec votre mail
extra:
    social:
        - icon: fontawesome/regular/envelope
          link: mailto:nizar.moussatat@ac-grenoble.fr
          name: √âcrire √† l'auteur
        - icon: fontawesome/brands/x-twitter
          link: https://x.com/zenxbear
          name: Tweeter √† l'auteur
        - icon: fontawesome/brands/discord
          link: https://discord.gg/zyvrR4P5Rr
          name: Joindre le discord  
        - icon: fontawesome/brands/github
          link: https://github.com/moussatat
          name: D√©p√¥t github
        - icon: fontawesome/solid/school 
          link: https://www.csja.fr/
          name: Lyc√©e Jeanne d'Arc
    # automatically exposed as a variable and can be used from the template
    # https://t.pxeger.com/mkdocs-material/reference/variables/
    # https://www.mkdocs.org/user-guide/configuration/#environment-variables 
    #CI_COMMIT_AUTHOR : "Nizar MOUSSATAT" 
    CI_PROJECT_URL : "https://github.com/moussatat/moussatat.github.io"  
    analytics:   
        provider : google
        property: G-BYF4FEE2HD
        anonymize_ip : True
        feedback:
          title: Avez-vous trouv√© le contenu de la page utile?
          ratings:
            - icon: material/emoticon-happy-outline
              name: Le contenu de la page est utile
              data: 1
              note: >-
                Merci pour votre avis !
            - icon: material/emoticon-sad-outline
              name: Le contenu peut √™tre am√©lior√©
              data: 0
              note: >- 
                Merci pour votre avis !
    consent:
        title: Consentement aux cookies
        description: >- 
            Ce site int√®gre des cookies analytics (pour des statistiques de fr√©quentation anonymes, les requ√™tes dans la barre de recherche) et des cookies de l'h√©bergeur <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement#our-use-of-cookies-and-tracking-technologies">GitHub</a>. 
            D√®s lors qu‚Äôune donn√©e est susceptible d‚Äô√™tre collect√©e, vous pouvez vous y opposer dans les choix de param√®tres ci-dessous.
        actions:
          - manage
          - accept
          - reject 
    generator: false
    
    
    
docs_dir: docs
 
nav:
    - Accueil : index.md   
    - Terminale : 
        - Ens. de sp√©cialit√© :  
            - üìÖ D√©roulement : teds/index.md
            - üéØ Cours et exercices :   teds/cours.md
            - üéì Evaluations :  teds/evaluations.md
            - üìã Progression : 
                - 2024-2025 : teds/progression2024.md 
        - EO Math√©matiques Expertes :  
            - üìÖ D√©roulement : eotx/index.md
            - üìö Cours et ‚úç exercices :  eotx/cours.md
            - üéì Evaluations :  eotx/evaluations.md
            - üìã Progression : 
                - 2024-2025 : eotx/progression2024.md 
            - üóÇÔ∏è Archives :
                - 2023-2024 :  eotx/archive2024.md
    - Premi√®re :  
        - üìÖ D√©roulement : 1eds/index.md
        - üéØ Cours et exercices :   1eds/cours.md
        - üéì Evaluations :  1eds/evaluations.md
        - üìã Progression : 
            - 2024-2025 : 1eds/progression2024.md
            - 2023-2024 : 1eds/progression2023.md
            - 2022-2023 : 1eds/progression2022.md
        - üóÇÔ∏è Archives :
            - 2023-2024 :  1eds/archive2024.md
            - 2022-2023 :  1eds/archive2023.md 
    - Seconde :  
        - üìÖ D√©roulement : 2gt/index.md
        - üéØ Cours et exercices :  2gt/cours.md
        - üéì Evaluations :  2gt/evaluations.md
        - üìã Progression 2024-2025 : 2gt/progression.md
        - üóÇÔ∏è Archives :
            - 2023-2024 :  2gt/archive2024.md
            - 2022-2023 :  2gt/archive2023.md
            - 2021-2022 :  2gt/archive2022.md 
    - üêç Python : 
        - Ressources pour la classe : python/index.md
        - Les bases pour la seconde : 
            - IDE et consoles : python/python-2gt-00/index.md
            - Types de valeurs et op√©rations : python/python-2gt-01/index.md
            - Variables et affectations : python/python-2gt-02/index.md
            - Librairies et compl√©ments : python/python-2gt-03/index.md
            - Les fonctions : python/python-2gt-04/index.md
            - Les instructions conditionnelles : python/python-2gt-05/index.md
            - Les boucles finies : python/python-2gt-06/index.md
            - Les boucles infinies : python/python-2gt-07/index.md
        - TD (seconde) :
            - Fonctions et tests : python/tp-2gt-01/index.md
        - TP (seconde) :
            - TP 01 : python/tp01.md 
    - ü§ñ SNT :  
        - Introduction : snt/index.md
        - Donn√©es structur√©es :
            - 1 - D√©couverte : snt/DonneesA.md
            - 2 - Structurer : snt/DonneesB.md
            - 3 - Traiter : snt/DonneesC.md
            - 4 - Projet : snt/DonneesD.md 
    - DNL :  
        - üìÖ D√©roulement : dnl/index.md
        - üóÇÔ∏è Archives :
            - 2023-2024 :  dnl/archive2024.md
            - 2022-2023 :  dnl/archive2023.md 
            - 2022-2023 :  dnl/archive2022.md 
    - Troisi√®me :  
        - üìÖ D√©roulement : 3c/index.md
        - üéØ Cours et exercices :   3c/cours.md
        - üéì Evaluations :  3c/evaluations.md
        - üìã Progression :  
            - 2023-2024 : 3c/progression2023.md 
        - üóÇÔ∏è Archives :
            - 2023-2024 :  3c/archive2024.md
            - 2022-2023 :  3c/archive2023.md 
            - 2022-2023 :  3c/archive2022.md 
    - Quatri√®me :  
        - üìÖ D√©roulement : 4b/index.md
        - üéØ Cours et exercices :  4b/cours.md
        - üéì Evaluations :  4b/evaluations.md
        - üìã Progression :  
            - 2022-2023 : 4b/progression2023.md 
        - üóÇÔ∏è Archives : 
            - 2022-2023 :  4b/archive2023.md 
            - 2022-2023 :  4b/archive2022.md 
    #- Liens : liens.md   
    #- About: about.md
    - Ô∏èüè∑Ô∏è tags : tags.md

not_in_nav:
    about.md
  

theme: 
    # name : readthedocs
    # name : material   
    name : pyodide-mkdocs-theme  
    custom_dir: overrides 
    font: false
    language: fr
    palette:  
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: red
          toggle:
            icon: material/weather-sunny # material/lightbulb # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
            name: Passer au mode nuit
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: red
          toggle:
            icon: material/weather-night # material/lightbulb-outline
            name: Passer au mode jour
    favicon: images/favicon.ico
    logo: images/logo.svg
    features:
        #- navigation.instant # conflit
        - navigation.tabs   #Pour avoir le menu vertical il fallait supprimer √ßa
        #- navigation.tabs.sticky # navigation tab will be lock below the header
        #- navigation.expand # when enabled all collapsible subsection are expanded
        #- navigation.sections
        - navigation.path  
        - navigation.footer
        #- toc.integrate 
        - toc.follow
        - navigation.top
        #- header.autohide
        - content.code.annotate   # Pour les annotations de code deroulantes avec +
        - content.code.copy  # Ajout apr√®s MAJ pour pouvoir copier du code 
        - content.code.select 
        - announce.dismiss
        - content.action.edit
        - content.action.view 
        - search.suggest
        - search.highlight
        
    icon:
        admonition:
            coeur: material/heart


plugins:
    - awesome-pages:   # Pour les fichiers .pages, toujours en premier
        # collapse_single_pages: false
        strict: false
    - open-in-new-tab
    - material/tags:
        tags_file: tags.md 
    - material/search # macros disables search  
    - pyodide_macros:
          # Vous pouvez ajouter ici tout r√©glage que vous auriez ajout√© concernant les macros:
          on_error_fail: true     # Il est conseill√© d'ajouter celui-ci si vous ne l'utilisez pas.
          build:
            python_libs:
                - turtle   
    # https://mkdocs-macros-plugin.readthedocs.io/en/stable/pages/#in-the-yaml-header-of-the-page
    #- macros :  # {{ macros_info() }}
    #      verbose: True   
    
#hooks:
    # https://www.mkdocs.org/user-guide/configuration/#hooks
    #- my_hooks.py  
    
markdown_extensions: 
    - toc:
        permalink: ‚öìÔ∏é
        toc_depth: 3   
    - def_list                      ## Les listes de d√©finition. 
    - md_in_html              # !!REQUIS!!
    - admonition              # !!REQUIS!! Blocs color√©s:  !!! info "ma remarque"
    - attr_list               # !!REQUIS!! Un peu de CSS et des attributs HTML, ex: { #id .class style="display:none" }
    - pymdownx.details        # !!REQUIS!! Admonition: ??? -> peuvent se d√©plier ; ???+ -> peuvent se replier.
    - pymdownx.emoji:         # !!REQUIS!! √âmojis:  :boom:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight      # !!REQUIS!! Coloration syntaxique du code  
    - pymdownx.inlinehilite   # !!REQUIS!! Coloration syntaxique pour les "code spans": `#!python  code_python`
    - pymdownx.snippets:      # !!REQUIS!! Inclusion de fichiers
        check_paths: true     # Fortement conseill√©...
        base_path: ["docs"]
    - pymdownx.tasklist:            # Cases √† cocher  - [ ]  et - [x] 
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables. 
    - pymdownx.superfences    # !!REQUIS!!
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex:    # !!REQUIS!! Pour LaTex
        generic: true
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note. 
    - pymdownx.critic           # https://squidfunk.github.io/mkdocs-material/reference/formatting/?h=keybo#adding-keyboard-keys
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.keys
    - pymdownx.pathconverter  :
        absolute: true # default: false 
    - pymdownx.magiclink:
          normalize_issue_symbols: true
          repo_url_shorthand: true
          user: zenxbear
          repo: moussatat.github.io 
        
# En remplacement de mkdocs-exclude. Tous les fichiers correspondant aux patterns indiqu√©s seront
# exclu du site final et donc √©galement de l'indexation de la recherche.
# Nota: ne pas mettre de commentaires dans ces lignes !
exclude_docs: |
    **/*_REM.md
    **/*.py 


extra_css: 
    # - xtra/stylesheets/ajustements.css  # ajustements
    - xtra/stylesheets/extra.css
    
validation:
  links:
    absolute_links: relative_to_docs
    
    
